### ISSUE TITLE
geodetic section units and flattening

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/automated-metadata-generation#1]
From this section, looks like semiaxis is in kilometers and should be meters.

Also as a sphere, denflat (Denominator_of_Flattening_Ratio) has always been awkward. It should be set to "infinity" (or even 0 to designate infinity). But the rule states "denflat > 0.0". So if you are interested in simply getting the record to pass validation you can use something stupid large like "1.0e+10" (or even larger). That was the value we used for LMMP FGDC. Fortunately, no one should really use FGDC to load a file's projection (it is just informational).

```
    <horizsys>
      <geodetic>
        <denflat>1.0</denflat>
        <semiaxis>1560.8</semiaxis>
        <ellips>Europa</ellips>
        <horizdn>0</horizdn>
      </geodetic>
```

recommended updates

```
    <horizsys>
      <geodetic>
        <denflat>1.0e+10</denflat>
        <semiaxis>1560800.0</semiaxis>
        <ellips>Europa</ellips>
        <horizdn>0</horizdn>
      </geodetic>
```

**Comment by jlaura** [comment]
@thareUSGS Should the den flat be 1.0e-10 instead of the above 1e+10?
